Signup, signin, JWT completed
wecode-bootcamp-korea/18-1st-KakaoVillains-backend pull request #2
Opened 2021-03-18 07:55 UTC by lwlkorea

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Sign in, Sign up, JWT 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- n/a
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- n/a

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-19 01:55 UTC, jamessoun93 commented
통신 결과 이미지 첨부 부탁드립니다.

2021-03-19 02:11 UTC, jamessoun93 requested changes

2021-03-19 02:11 UTC, jamessoun93 commented on account/views.py
> +            if ('@' and '.') not in email:
이 조건 테스트해보시면 정상적으로 작동 안할텐데요! 수정해주세요~

2021-03-19 02:11 UTC, jamessoun93 commented on account/views.py
> +            if username == '':
만약 username 을 넘겨받았을 경우 빈 스트링이면 안된다의 의미인건가요?

2021-03-19 02:11 UTC, jamessoun93 commented on account/views.py
> +            return JsonResponse({'result': 'SUCCESS'}, status=200)
CREATED 를 의미하는 status code 로 변경해주세요.

2021-03-19 02:11 UTC, jamessoun93 commented on account/views.py
> +
objects.get() 메소드를 활용하실 때는 DoesNotExist 외에 잡아주셔야하는 exception 이 또 있습니다. 찾아서 추가해주세요.

2021-03-19 02:11 UTC, jamessoun93 commented on account/views.py
> +                return JsonResponse({"message":"KEY_ERROR"}, status=400)
위에서는 email 을 get 으로 받고 여기서는 None 일때 400 을 리턴해주는것은 흐름이 맞지가 않겠죠? 의도하셨던 바에 맞게 로직 수정해주세요.

그리고 기본적으로 파이썬의 `NoneType` 은 값이 존재하지 않고 메모리 상 딱 하나만 존재하기 때문에 `==` 으로 비교하지 않습니다.
동일한 메모리 주소에 저장된 객체인지 확인하는 `is` 를 활용해주세요.

2021-03-19 06:02 UTC, lwlkorea commented on account/views.py
> +
multiple object

2021-03-21 05:25 UTC, lwlkorea commented on account/views.py
> +            if ('@' and '.') not in email:
왜 'and' 로 썼는지 모르겠네요... 'or'로 수정하니 잘 됩니다.

2021-03-21 06:17 UTC, lwlkorea commented on account/views.py
> +            if username == '':
네. username 이 안 들어왔을때와 별개로 빈 스트링이 들어왔을 때 반환하려고 따로 넣었습니다.

2021-03-21 06:33 UTC, lwlkorea commented on account/views.py
> +            return JsonResponse({'result': 'SUCCESS'}, status=200)
201 로 수정했습니다.

2021-03-21 06:38 UTC, lwlkorea commented on account/views.py
> +
MultipleObjectsReturned 추가했습니다.

2021-03-21 06:39 UTC, lwlkorea commented on account/views.py
> +
그런데 import 안 해줘도 오류가 나지 않는데 따로 import 안 해도되나요?

2021-03-21 06:51 UTC, lwlkorea commented on account/views.py
> +                return JsonResponse({"message":"KEY_ERROR"}, status=400)
인증요건이 충족되지 못한것이라 401 인가요? 그렇게 수정 했어요. + 그리고 이메일을 안넣으면 바로 DoesNotExist exception으로 가버립니다. 혹시 이메일을 안 넣은 경우만 따로 거를 수는 없나요?

2021-03-22 01:41 UTC, jamessoun93 commented
> 통신 결과 이미지 첨부 부탁드립니다.

2021-03-22 09:48 UTC, jamessoun93 commented on account/views.py
> +
넵 해당 모델 클래스에서 직접 접근 가능해서 import 불필요합니다!

2021-03-22 09:53 UTC, jamessoun93 commented
추가 수정사항 구두로 전달.

2021-03-22 10:07 UTC, jamessoun93 approved these changes
LGTM

2021-03-22 10:07 UTC, merged