[허정원]Feature/feed 피드 관련 기능 구현
wecode-bootcamp-korea/18-1st-KakaoVillains-backend pull request #4
Opened 2021-03-22 12:50 UTC by HurJungWon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 피드 관련 뷰 작성 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- feed.views FeedIndexView 
get 메소드를 통해 feed 전체 데이터를  최신순으로 정렬해 4개씩 가져오며 최신 댓글, 추천상품을 같이 가져온다. 

- feed.views FeedView
get 메소드를 통해 특정 feed에 관련된 데이터, 댓글, 대댓글을 가져온다.

- feed.views ReplyView
post 메소드를 통해 인증된 유저의 댓글을 등록함
delete 메소드를 통해 인가된 유저의 댓글을 삭제함
patch 메소드를 통해 인가된 유저의 댓글을 수정함

- feed.views FeedLikeView
post 메소드를 통해 해당 유저가 해당 피드의 좋아요 테이블에 존재한다면 취소하고 없다면 등록한다.

- feed.views ReplyLikeView
post 메소드를 통해 유저가 해당 댓글의 좋아요 테이블에 존재한다면 취소하고 없다면 등록한다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-22 14:28 UTC, HurJungWon commented
## 전체 피드 중 4개씩 가져온다.
![스크린샷 2021-03-22 오후 9 29 05](https://user-images.githubusercontent.com/71869837/112004022-c307f080-8b64-11eb-9eab-37fc87638300.png)

## 특정 피드만 가져온다.
![스크린샷 2021-03-22 오후 9 29 49](https://user-images.githubusercontent.com/71869837/112004123-dca93800-8b64-11eb-8875-c65585a00f04.png)

## 인증 받은 유저 댓글 등록
![스크린샷 2021-03-22 오후 9 31 23](https://user-images.githubusercontent.com/71869837/112004444-285be180-8b65-11eb-93f9-9e0c59c7be2e.png)


## 인가 받은 유저 댓글 삭제
<img width="720" alt="스크린샷 2021-03-22 오후 9 33 15" src="https://user-images.githubusercontent.com/71869837/112004767-72dd5e00-8b65-11eb-8ee1-efe587fee62c.png">
* 인가 받지 못한 유저 댓글 삭제 오류
<img width="746" alt="스크린샷 2021-03-22 오후 9 34 41" src="https://user-images.githubusercontent.com/71869837/112004859-8ab4e200-8b65-11eb-8278-a89b8ccfea60.png">
* 인가 받은 유저 댓글 내용 수정
<img width="746" alt="스크린샷 2021-03-22 오후 9 34 55" src="https://user-images.githubusercontent.com/71869837/112005031-b768f980-8b65-11eb-9c1d-f7841e0cdb40.png">

## 인증 받은 유저 피드 좋아요 기능 (body 값은 무시해주세요)
<img width="746" alt="스크린샷 2021-03-22 오후 9 36 11" src="https://user-images.githubusercontent.com/71869837/112005165-d8c9e580-8b65-11eb-9cfd-790f48843da4.png">
* 피드 좋아요 테이블에 유저가 이미 존재한다면 삭제기능
<img width="746" alt="스크린샷 2021-03-22 오후 9 36 37" src="https://user-images.githubusercontent.com/71869837/112005303-fac36800-8b65-11eb-984f-3c21c4d4fba1.png">

## 인증 받은 유저 댓글 좋아요 기능
<img width="746" alt="스크린샷 2021-03-22 오후 9 37 01" src="https://user-images.githubusercontent.com/71869837/112005408-129aec00-8b66-11eb-8a01-734417989f03.png">
* 댓글 좋아요 테이블에 유저가 이미 존재한다면 삭제기능 
<img width="746" alt="스크린샷 2021-03-22 오후 9 37 11" src="https://user-images.githubusercontent.com/71869837/112005709-5b52a500-8b66-11eb-80a0-291c7ff0035f.png">

2021-03-23 02:59 UTC, jamessoun93 requested changes

2021-03-23 02:59 UTC, jamessoun93 commented on .vscode/settings.json
> +}
이런 정보는 개발환경 세팅 관련 폴더 및 파일이니 없애주세요!

2021-03-23 02:59 UTC, jamessoun93 commented on db_up.py
> +
csv 파일 혹은 uploader 용 스크립트 파일은 해당 프로젝트 상 git 으로 공유하지 마시고 따로 직접 공유해주세요!

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +        feeds       = Feed.objects.all().order_by('-created_at')[feed_start:feed_end]
pagination 로직 잘 구현해주셨네요! 👍

이 기능을 구현하는데 정말 여러가지 방법이 있지만 지금 구현하신 상태로 보면 우선 path params 를 활용하셔서 매번 
`feed/feeds/0`, `feed/feeds/1` 이런식으로 요청이 들어와야하는데 이런 로직은 query params 를 활용해주시면 훨씬 더 깔끔하고 더 RESTful하게 처리해줄 수 있습니다. 그리고 mysql syntax에 `limit` 과 `offset` 이라는게 있는데, 이런 것들을 활용하여 더 연관성있게 로직을 작성해주실 수 있습니다. 

적용해보세요!

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +
여기도 list comprehension 적용해주세요!

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +            user               = User.objects.get(id=feed.user_id)
feed 가 이미 user 를 참조하고 있으니 굳이 User 모델을 참조하여 get 을 해올 필요가 있을까요?! 다른 방법에는 어떤게 있을까요?

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +            reply              = Reply.objects.filter(feed_id=feed.id, parent_id=None).order_by('created_at').last()
대댓글이 아닌 일반 댓글 중 가장 최근 댓글을 찾으시는건가요? 가져와서 사용을 하시려는건지 단순 댓글 존재 여부만 확인하시는건지 궁금합니다.

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +            recommend_products = Feed.objects.get(id=feed.id).products.all()
여기서도 이미 feeds 를 순회하며 feed 객체에 대한 정보를 가지고 있을텐데 또 feed.id 로 Feed 모델 조회할 필요가 없겠죠?

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +                reply_content  = reply.content
ternary operator 적용하면 더 깔끔해지겠네요!

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +                    recommend_product.append(product_dict)
이부분은 list comprehension 적용해주세요! 훨씬 깔끔해지고 약간의 성능 boost 도 기대할 수 있습니다.

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +                    recommend_product.append(product_dict)
어짜피 recommend_products 는 쿼리셋 리스트기 때문에 아무것도 존재하지 않는다면 결과 리스트가 빈 리스트인 상태로 마무리되기 때문에 굳이 아무것도 없을때의 조건을 걸어줄 필요가 없습니다.

2021-03-23 02:59 UTC, jamessoun93 commented on feed/views.py
> +
여기도 FeedIndexView 리뷰내용과 중복내용이 많아서 확인하시고 수정해주시면 추가 리뷰 진행하겠습니다!

2021-03-23 04:29 UTC, HurJungWon commented on feed/views.py
> +        feeds       = Feed.objects.all().order_by('-created_at')[feed_start:feed_end]
`feed?page=숫자`
이란식으로 query params 식으로 바꾸었습니다!!!

```python
        limit   = 4
        offset  = limit * page
        feeds   = Feed.objects.all().order_by('-created_at')[offset:offset+limit]
```
위에 처럼 변수이름 변경하고 적용했습니다!!

2021-03-23 04:32 UTC, HurJungWon commented on feed/views.py
> +            user               = User.objects.get(id=feed.user_id)
feed.user로 간단하게 적용할 수 있네요 ㅎㅎ

2021-03-23 04:39 UTC, HurJungWon commented on feed/views.py
> +            reply              = Reply.objects.filter(feed_id=feed.id, parent_id=None).order_by('created_at').last()
대댓글이 아닌 댓글 중 가장 최신 댓글을 가져와서 댓글의 유저이름과 내용을 전달하려고 합니다!

2021-03-23 05:03 UTC, HurJungWon commented on feed/views.py
> +                reply_content  = reply.content
```python
reply_username = reply.user.username if reply else ''
reply_content  = reply.content if reply else ''
```
이렇게 변경했습니다!!

2021-03-23 05:13 UTC, HurJungWon commented on feed/views.py
> +                    recommend_product.append(product_dict)
```python
recommend_product = [
                {
                    'name'        : product.name,
                    'price'         : round(product.price),
                    'image_url' : product.productimage_set.first().image_url
                } for product in recommend_products
            ]
```
이러식으로 변경했습니다!!

2021-03-23 05:19 UTC, jamessoun93 commented on feed/views.py
> +        feeds       = Feed.objects.all().order_by('-created_at')[feed_start:feed_end]
따봉!!! 역시 정원님!

2021-03-23 06:17 UTC, HurJungWon commented on feed/views.py
> +
```python
result = [
                {
                    'id'                 : feed.id,
                    'username'           : user.username,
                    'title'              : feed.title,
                    'content'            : feed.content,
                    'image_url'          : image_url,
                    'profile_picture'    : user.profile_picture_url,
                    'like_count'         : feed.like_count,
                    'datetime'           : feed.created_at.strftime('%Y.%m.%d'),
                    'reply_count'        : feed.reply_count,
                    'reply_username'     : reply_username,
                    'reply'              : reply_content,
                    'recommend_products' : recommend_product,
                } for feed in feeds
            ]
```

2021-03-23 07:10 UTC, HurJungWon commented on feed/views.py
> +
중복내용 수정했습니다.
다른 뷰도 중복되는 내용 수정하겠습니다!!

2021-03-24 02:11 UTC, jamessoun93 requested changes

2021-03-24 02:11 UTC, jamessoun93 commented on feed/views.py
> +        offset  = limit * page
이런 정보들은 중간에 바뀌는 값이 아니기 때문에 상수라는 의미로 대문자로 선언해주세요!

2021-03-24 02:11 UTC, jamessoun93 commented on feed/views.py
> +            ]
하나의 피드 데이터를 리턴해주는 로직인데 dictionary 를 불필요하게 list 로 감싸주실 필요가 없겠죠?

2021-03-24 02:11 UTC, jamessoun93 commented on feed/views.py
> +            return JsonResponse({'message': 'JSON_DECODE_ERROR'}, status=400)
만약 feed_id 가 없을때는 어떻게 되나요?

2021-03-24 02:11 UTC, jamessoun93 commented on feed/views.py
> +                feed.save()
여기서는 exists() 메소드를 활용해주시는게 가독성 측면에서 더 좋다고 생각합니다.

2021-03-24 02:11 UTC, jamessoun93 commented on feed/views.py
> +                reply.save()
여기도 마찬가지입니다!

2021-03-24 02:37 UTC, HurJungWon commented on feed/views.py
> +            ]
데이터를 받는 프론트 입장에서 전체 피드를 받는 형식과 동일하게 하는게 편하겠다고 생각했습니다!!
프론트랑 상의하고 수정하겠습니다!

2021-03-24 02:41 UTC, HurJungWon commented on feed/views.py
> +            return JsonResponse({'message': 'JSON_DECODE_ERROR'}, status=400)
query params가 없으면 none 으로 지정되기 때문에 feed 오브젝트를 가져오는 상황에서 
```python
except Feed.DoesNotExist 
```
로 처리되고 있습니다.

2021-03-24 02:49 UTC, HurJungWon commented on feed/views.py
> +                feed.save()
feed_likes 테이블의 객체를 삭제하려고 feed_like 라는 변수를 이용했는데 
exists()메소드를 활용하면 유저나 피드 객체를 이용해서 다시 feed_likes 객체를 불러와야 할 거 같은데 
다른 방법이 있는지 생각해보고 수정하겠습니다!!

2021-03-24 09:00 UTC, jamessoun93 commented on feed/views.py
> +            ]
네네 이부분은 프론트에서 수정해야하는 부분입니다. 그렇게 전달해주세요.

2021-03-25 00:31 UTC, jamessoun93 requested changes

2021-03-25 00:31 UTC, jamessoun93 commented on feed/views.py
> +        for feed in feeds:
list comprehension 적용해주세요!

2021-03-25 00:31 UTC, jamessoun93 commented on feed/views.py
> +        feeds   = Feed.objects.all().order_by('-created_at')[OFFSET:OFFSET+LIMIT]
만약 존재하지 않는 인덱스까지 slice 한다면 무슨일이 발생할까요? 예를들어 우리는 제품이 10개밖에 없는데 그 외에 것들을 요청할때에 대한 예외처리가 되어있어야 할 것 같습니다.

2021-03-25 00:31 UTC, jamessoun93 commented on feed/views.py
> +            result = [
이 부분은 말씀드렸다시피 리스트로 감싸줄 필요가 없는 부분이고, 프론트에서도 그렇게 처리가 되어있으면 안되는 부분이기 때문에 꼭 프론트에서도 수정할 수 있도록 전달해주세요.

2021-03-25 01:39 UTC, HurJungWon commented on feed/views.py
> +        for feed in feeds:
list comprehension 을 쓰면 안에 있는 reply 관련 값들의 식이 아래처럼 너무 길어집니다.
```python
'reply_username' : feed.reply_set.filter(parent_id=None).order_by('-created_at').first().user.username if feed.reply_set.filter(parent_id=None).order_by('-created_at').first() else ''

'reply_content' : feed.reply_set.filter(parent_id=None).order_by('-created_at').first().content if feed.reply_set.filter(parent_id=None).order_by('-created_at').first() else ''
```

그래서 밖에서 함수 선언해서 호출 하는 식으로 적용했는데 결과는 나오지만 효율적인지 잘 모르겠습니다.
아침부터 고생 많으십니다 !!! 퐈이팅!!

2021-03-25 01:45 UTC, HurJungWon commented on feed/views.py
> +            result = [
예 프론트랑 상의했는데 바로 수정하기로 했습니다!

2021-03-25 02:25 UTC, HurJungWon commented on feed/views.py
> +        feeds   = Feed.objects.all().order_by('-created_at')[OFFSET:OFFSET+LIMIT]
OFFSET 값이 전체 피드 숫자를 초과 할 때 return 해주었습니다.!

2021-03-25 06:50 UTC, jamessoun93 requested changes

2021-03-25 06:50 UTC, jamessoun93 commented on feed/views.py
> +            return JsonResponse({'message': 'INVALID FEED'}, status=400)
조건 처리 말씀드린대로 너무 잘 해주셨는데요! 예외처리를 해줘야하는 부분이지만 자주 발생하지 않을 에러이기 때문에 굳이 항상 거치를 로직으로 이렇게 처리해주시는것보다 그냥 list index out of range 를 뜻하는 exception 으로 처리해주세요!

2021-03-25 08:26 UTC, HurJungWon commented on feed/views.py
> +            return JsonResponse({'message': 'INVALID FEED'}, status=400)
찾고 있었는데 감사합니다!!

2021-03-25 08:50 UTC, jamessoun93 commented
충돌 해결해주세요! @HurJungWon

2021-03-25 10:37 UTC, jamessoun93 commented
LGTM!

2021-03-25 10:37 UTC, merged