[이왕록]Feature/product 완료
wecode-bootcamp-korea/18-1st-KakaoVillains-backend pull request #5
Opened 2021-03-23 11:54 UTC by lwlkorea

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 프로덕트 앱 완성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 제품상세, 리뷰, 라이크, 카테고리 필터 & 정렬, 검색 완성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 주석으로 달아놓았습니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-24 08:53 UTC, jamessoun93 requested changes

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +            reviews        = Review.objects.filter(product_id=product_id)
어제 말씀드린 것 같은데 이렇게 다 따로따로 찾지 마시고 product 와의 관계를 이용하여 데이터 가져오는 방식으로 변경해주세요.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +                image_list.append(image_url.image_url)
list comprehension 적용해주세요.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +                token = request.headers.get('Authorization')
데코레이터 PR 머지했으니 이 부분 변경해주세요.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +                rating_value = rating_value - (rating_value % 1) + 1
음.. 이런 코드는 순서도 맞지 않고, 가독성도 좋지 못합니다.

우선 `if ... elif ... elif` 조건들의 순서상 문제가 있습니다. `rating_value % 1 < 0.1` 을 가장 먼저 걸러줘야 정상작동할텐데 지금은 `0.1` 보다 작더라도 `0.3` 보다 작다는 첫번째 조건에 다 걸리게 되겠죠?

그리고 소숫점 자리를 `0` 과 `5`로 맞게 떨어지게 하고싶은것이라면 원하는 값을 `round()` 함수를 사용하여 `round` 해주신 후 `2`를 곱한 값에, `float` 냐 `int` 냐에 따라 `2.0` 혹은 `2`로 나눠주면 됩니다. 

아래처럼요.
```python
avg_rating = round(rating_value * 2) / 2.0
```

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +            character_related_products    = [{"image_url":ProductImage.objects.filter(product=related_product).first().image_url, "name":related_product.name, "price":related_product.price, "discount
list comprehension 을 사용하실때에는 가독성이 중요한데 이렇게 한줄로 작성해놓으시면 그 효과가 하나도 없어집니다. 적절한 줄바꿈과 들여쓰기를 통해 개선해주세요.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +                    related_products.append(related_product)
list comprehension 적용해주세요.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +            }]
list 로 감싸주시는 이유가 있나요? 항상 하나의 dictionary 만 리턴해줄텐데 list 를 활용할 필요가 없습니다.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +            )
단일객체 업데이트라면 instance 를 활용하여 save() 해주시는 방법으로 변경해주세요.

2021-03-24 08:53 UTC, jamessoun93 commented on product/views.py
> +class CategoryManage(View):
이 부분은 어제 대화 나눈대로 더 올바른 방법이 있는데 해보고 싶으신 방향대로 작성해보기로 하셨기 때문에 리뷰 안하고 나중에 모델 수정 후 로직 새로 작성하시면 그때 리뷰 진행합니다.

2021-03-24 11:04 UTC, lwlkorea commented on product/views.py
> +            reviews        = Review.objects.filter(product_id=product_id)
_set.all() 사용해서 수정했습니다.

2021-03-24 11:18 UTC, lwlkorea commented on product/views.py
> +            }]
없애려 했는데, 저희는 간단하게 리스트만 없애면 되는데 프론트에서 이미 저렇게 짠 이후에 고치는데 시간이 많이 든다 하여 이렇게 했습니다.

2021-03-24 11:19 UTC, lwlkorea commented on product/views.py
> +                image_list.append(image_url.image_url)
적용했습니다.

2021-03-24 11:35 UTC, lwlkorea commented on product/views.py
> +                token = request.headers.get('Authorization')
@indicator 사용하도록 변경했습니다.

2021-03-24 11:36 UTC, lwlkorea commented on product/views.py
> +                rating_value = rating_value - (rating_value % 1) + 1
오! 수정했습니다. 천재시네요

2021-03-24 11:40 UTC, lwlkorea commented on product/views.py
> +            character_related_products    = [{"image_url":ProductImage.objects.filter(product=related_product).first().image_url, "name":related_product.name, "price":related_product.price, "discount
수정했습니다.

2021-03-24 11:45 UTC, lwlkorea commented on product/views.py
> +                    related_products.append(related_product)
중복된 값을 제외하려고 related_products 리스트를 새로 만들어서 조건문 not in 으로 걸러서 집어넣으려 하는데 아래처럼 list comprehension 을 하면 작동이 안됩니다. 

`            related_products = [related_product for related_product in temp if related_product not in related_products]
`

2021-03-24 11:51 UTC, lwlkorea commented on product/views.py
> +            )
수정했습니다.

2021-03-24 11:52 UTC, lwlkorea commented on product/views.py
> +class CategoryManage(View):
헙,,, 이게 거의 절반이고 뒤에 서치도 있는데....

2021-03-25 02:09 UTC, jamessoun93 commented on product/views.py
> +            }]
넵 올바른 방법 아니니 프론트분들한테도 수정하라고 전달해주세요.

2021-03-25 03:36 UTC, jamessoun93 reviewed
왕록님 아무래도 구두로 리뷰를 드려야할 것 같아서 오후에 aws 세션 후 뵐게요.

2021-03-25 07:28 UTC, merged